// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmXT6irJ48GKhcZpe7ypISxl7ge7cihv4',
    appId: '1:436252897881:web:75ef31bd130743cc16f748',
    messagingSenderId: '436252897881',
    projectId: 'khatri-alter',
    authDomain: 'khatri-alter.firebaseapp.com',
    storageBucket: 'khatri-alter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO63K5miiFBVWBApf3d12qP3i9LGMYvxs',
    appId: '1:436252897881:android:41ea2cb38653ff5016f748',
    messagingSenderId: '436252897881',
    projectId: 'khatri-alter',
    storageBucket: 'khatri-alter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYhM7chI1jZgpLQw5xUjNLWVWRVsytMio',
    appId: '1:436252897881:ios:47c6528ccad205bc16f748',
    messagingSenderId: '436252897881',
    projectId: 'khatri-alter',
    storageBucket: 'khatri-alter.appspot.com',
    iosBundleId: 'com.stech.khatriAlter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYhM7chI1jZgpLQw5xUjNLWVWRVsytMio',
    appId: '1:436252897881:ios:e8f7b4ec2c89963d16f748',
    messagingSenderId: '436252897881',
    projectId: 'khatri-alter',
    storageBucket: 'khatri-alter.appspot.com',
    iosBundleId: 'com.stech.khatriAlter.RunnerTests',
  );
}
